DROP TABLE IF EXISTS pet_growth_media;
DROP TABLE IF EXISTS pet_growth_events;
DROP TABLE IF EXISTS pet_weights;
DROP TABLE IF EXISTS pet_birthday_blessings;
DROP TABLE IF EXISTS pet_birthday_media;
DROP TABLE IF EXISTS pet_birthday_records;
DROP TABLE IF EXISTS pet_vaccines;
DROP TABLE IF EXISTS pet_diseases;
DROP TABLE IF EXISTS pet_health;
DROP TABLE IF EXISTS pet_questions;
DROP TABLE IF EXISTS pet_personality;
DROP TABLE IF EXISTS pet_certificates;
ALTER TABLE pets DROP COLUMN avatar_asset_id;
ALTER TABLE pets DROP COLUMN cover_asset_id;
ALTER TABLE pets DROP COLUMN breed;
ALTER TABLE pets DROP COLUMN gender;
ALTER TABLE pets DROP COLUMN sterilized;
ALTER TABLE pets DROP COLUMN birthday;
ALTER TABLE pets DROP COLUMN home_date;
